Trials Project Pull Request
pulgosodog/Review-one-of-your-past-projects pull request #1
Opened 2023-05-03 19:58 UTC by pulgosodog

Opening a pull request to be reviewed by me to put in practice code reviewing.

2023-05-03 20:03 UTC, pulgosodog commented on css/style.css
> +width: 600px;
Kindly change the width to the equivalent on vw to make it a responsive website.

2023-05-03 20:30 UTC, pulgosodog reviewed
Kindly review the marked suggested changes before merging.

2023-05-03 20:30 UTC, pulgosodog commented on css/style.css
> +width: 600px;
Indent a space after the header tag, get all properties on a new line with an indentation of 2 spaces at the beginning for each new line, and erase all blank lines in between each new property line. Be sure to also add a blank line in between tags.
Example:
![image](https://user-images.githubusercontent.com/115130832/236039575-964b503e-ea01-4dbe-a667-32bee42587e2.png)

2023-05-03 20:30 UTC, pulgosodog commented on css/style.css
> +h1{
Add responsive values such as **vw** or **%** to the h1, h5s, and p tags.

2023-05-03 20:30 UTC, pulgosodog commented on index.html
> +        <a href="#" class="btn btn-primary">Add to cart</a>
Wrap the <a> tag with a <button> tag, and also center aligns the button.
![image](https://user-images.githubusercontent.com/115130832/236041413-ea53f6a2-4e42-4ae6-a57e-bccc9b0a6edb.png)

2023-05-03 20:30 UTC, pulgosodog commented on index.html
> +<section id="products">  <div class="row">
Add a margin to the sides of the product section.
![Screenshot 2023-05-03 2 26 21 PM](https://user-images.githubusercontent.com/115130832/236042243-77d50ba8-1991-4741-8f3a-a7818aa99a72.png)

2023-05-03 20:30 UTC, pulgosodog commented on index.html
> +<section id="products">  <div class="row">
Add a title to the products section.

2023-05-03 21:18 UTC, NatiG25 requested changes
Hi @pulgosodog, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
:heavy_check_mark: Great job using inline comments.
:heavy_check_mark: Mentioned nice suggestions.
![](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a summary for your review.
- Using gifs or emojis.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-03 21:18 UTC, NatiG25 commented on index.html
> +<section id="products">  <div class="row">
- [ ] Kindly, check the previously mentioned **required change**, in order to, deliver a better code review :rocket:.

2023-05-03 21:18 UTC, NatiG25 commented on index.html
> +<section id="products">  <div class="row">
- [ ] Kindly, check the previously mentioned **required change**, in order to, deliver a better code review :rocket:.

2023-05-03 21:18 UTC, NatiG25 commented on index.html
> +        <h5 class="card-title">Special title treatment</h5>
- [ ] Kindly, check the previously mentioned **required change**, in order to, deliver a better code review :rocket:.

2023-05-03 21:18 UTC, NatiG25 commented on index.html
> +        <a href="#" class="btn btn-primary">Add to cart</a>
- [ ] I highly recommend adding more clarity to your suggestions because you didn't mention which tag to wrap with & how to center the button. Clear suggestions or comments are essential for a smooth code review. The person getting reviewed will spend less time trying to understand & implement the suggestions mentioned.

- [ ] Kindly, also check the first mentioned **required change**, in order to, deliver a better code review :rocket:.

2023-05-04 01:53 UTC, pulgosodog commented on css/style.css
> +h1{
Noted! Edited the comment and added "Please consider" to make it more polite and less frustrating.
I will try to incorporate "why" in other comments since this one is just bad practice without an explanation or thought behind it.

2023-05-04 01:56 UTC, pulgosodog commented on index.html
> +        <h5 class="card-title">Special title treatment</h5>
Noted! I added "why on this one.
Updated comment change:
"Why does this h5 have that name? 
Kindly consider..."

2023-05-04 01:58 UTC, pulgosodog commented on css/style.css
> +width: 600px;
Noted! Not sure what is outside of this comment that is related, but as this review is **optional**, I'm going to leave it like that, I will also have it in mind for future code review for best practices.

2023-05-04 02:07 UTC, pulgosodog commented on index.html
> +        <a href="#" class="btn btn-primary">Add to cart</a>
Oh sorry, I use <> at the corners of the mentioned tags and got them hidden.
![image](https://user-images.githubusercontent.com/115130832/236094672-85223be5-98b9-4d7c-906b-bf978e705150.png)

2023-05-04 02:09 UTC, pulgosodog commented on index.html
> +        <a href="#" class="btn btn-primary">Add to cart</a>
Implemented requested changes! 🙌

2023-05-04 02:09 UTC, pulgosodog commented on index.html
> +<section id="products">  <div class="row">
Updated comment!

2023-05-04 02:10 UTC, pulgosodog commented on index.html
> +<section id="products">  <div class="row">
Updated comment!

2023-05-04 03:08 UTC, abdallahmalima requested changes
Hi @pulgosodog , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![A little bit more](https://user-images.githubusercontent.com/20554583/208236462-13ccd332-b921-416b-a8a9-b831ebd7c79b.gif)


 ## Highlights
- Polite communication ✔
- Clear comments ✔

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-04 03:08 UTC, abdallahmalima commented on index.html
> +<section id="products">  <div class="row">
- [OPTIONAL ] 🙏 Please add the reason why you suggest changes. The why may be obvious to you as a reviewer, but not necessarily to the person😣 receiving the code review.

2023-05-07 05:39 UTC, pulgosodog commented on css/style.css
> +h1{
Just updated the coment

2023-05-07 05:39 UTC, pulgosodog commented on css/style.css
> +width: 600px;
Just updated the comment.

2023-05-07 05:40 UTC, pulgosodog commented on index.html
> +        <h5 class="card-title">Special title treatment</h5>
Just updated the comment

2023-05-07 05:41 UTC, pulgosodog commented on index.html
> +<section id="products">  <div class="row">
Just updated the comment.

2023-05-07 05:50 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @pulgosodog, 👋 👋  

Your project is complete! Great job for following the project requirement🥇and implementing the changes requested by the previous reviewers. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

## Good Points 👍

- Give a better review as requested by previous reviewers ✔️

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-07 05:56 UTC, merged